sudo: required
services:
  - docker

before_install:
  # Build test version of client tests
  - echo This is where you should build your test images.

script:
  # Run tests for client
  # - docker run -e CI=true sntshk/complex-client:test npm test
  - echo This is where you run test command on above build image.

after_success:
  # Build production version of images
  - docker build -t sntshk/complex-client ./client
  - docker build -t sntshk/complex-nginx ./nginx
  - docker build -t sntshk/complex-server ./server
  - docker build -t sntshk/complex-worker ./worker

  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push production version of images to Docker Hub
  - docker push sntshk/complex-client
  - docker push sntshk/complex-nginx
  - docker push sntshk/complex-server
  - docker push sntshk/complex-worker
