sudo: required
language: generic
services:
  - docker

before_install:
  # Build test version of client tests
  - docker build -t $DOCKER_ID/complex-client:test -f ./client/Dockerfile.dev ./client

script:
  # Run tests for client
  - docker run -e CI=true $DOCKER_ID/complex-client:test npm test
